# Generated by Django 4.0 on 2022-01-05 16:14

import config.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_created=True)),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(config.mixins.TranslateMixin, models.Model),
        ),
    ]
